services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: sangtran
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
